hackathon_user:
    resource: "@HackathonUserBundle/Controller/"
    type:     annotation
    prefix:   /user

hackathon_front:
    resource: "@HackathonFrontBundle/Controller/"
    type:     annotation
    prefix:   /

hotels:
    type: rest
    prefix:   /api
    resource: Hackathon\ApiBundle\Controller\HotelsController

places:
    type: rest
    prefix:   /api
    resource: Hackathon\ApiBundle\Controller\PlacesController

avis:
    type: rest
    prefix:   /api
    resource: Hackathon\ApiBundle\Controller\AvisController
