<?php

namespace Hackathon\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceTypeRepository extends EntityRepository
{
}
